angular.module(appName)
.controller('calendarCtrl',function($scope,calendar,mode,MEMO_LIMIT){//{{{
    $scope.calendar=calendar;
    $scope.nextMonth=function(){//{{{
        calendar.month++;
        calendar.selected=null;
        if(calendar.month+1>12){
            calendar.year+=1;
            calendar.month-=12;
        }
        mode.editsEvent=false;
    };//}}}
    $scope.lastMonth=function(){//{{{
        calendar.month--;
        calendar.selected=null;
        if(calendar.month+1<1){
            //1月より前==前年の12月だから繰り下げ
            if(calendar.year-1<MEMO_LIMIT){
                alert(MEMO_LIMIT+'年より以前はパフォーマンスの関係で表示できません。');
                //calendar()関数のメモ化の関係
                calendar.month+=1;
            }else{
                calendar.month+=12;
                calendar.year-=1;
            }
        }
        mode.editsEvent=false;
    };//}}}
    $scope.nextYear=function(){//{{{
        calendar.year++;
        calendar.selected=null;
        mode.editsEvent=false;
    };//}}}
    $scope.lastYear=function(){//{{{
        if(calendar.year-1<MEMO_LIMIT){
            alert(MEMO_LIMIT+'年より以前はパフォーマンスの関係で表示できません。');
        }else{
            calendar.year--;
            calendar.selected=null;
        }
        mode.editsEvent=false;
    };//}}}
    $scope.dates=['日','月','火','水','木','金','土'];
})//}}}
;
