angular.module(appName)
.controller('calendarCtrl',['$scope','calendar','mode',function($scope,calendar,mode){//{{{
    $scope.calendar=calendar;
    $scope.nextMonth=function(){//{{{
        $scope.calendar.month++;
        $scope.calendar.selected=null;
        if($scope.calendar.month+1>12){
            $scope.calendar.year+=1;
            $scope.calendar.month-=12;
        }
        mode.editsEventForm=false;
    };//}}}
    $scope.lastMonth=function(){//{{{
        $scope.calendar.month--;
        $scope.calendar.selected=null;
        if($scope.calendar.month+1<1){
            //1月より前==前年の12月だから繰り下げ
            if($scope.calendar.year-1<MEMO_LIMIT){
                alert(MEMO_LIMIT+'年より以前はパフォーマンスの関係で表示できません。');
                //calendar()関数のメモ化の関係
                $scope.calendar.month+=1;
            }else{
                $scope.calendar.month+=12;
                $scope.calendar.year-=1;
            }
        }
        mode.editsEventForm=false;
    };//}}}
    $scope.nextYear=function(){//{{{
        $scope.calendar.year++;
        $scope.calendar.selected=null;
        mode.editsEventForm=false;
    };//}}}
    $scope.lastYear=function(){//{{{
        if($scope.calendar.year-1<MEMO_LIMIT){
            alert(MEMO_LIMIT+'年より以前はパフォーマンスの関係で表示できません。');
        }else{
            $scope.calendar.year--;
            $scope.calendar.selected=null;
        }
        mode.editsEventForm=false;
    };//}}}
    $scope.dates=['日','月','火','水','木','金','土'];
}])//}}}
;
