angular.module(appName).factory("eventCal",["group","user","calF","$mdToast",function(t,q,v,A){function w(c){A.show(A.simple().content(c).position("top right"));console&&console.error&&console.error(c)}function x(c,a,g){if("private"!==c&&!t[c])return[];var e=[],f=[];"private"===c?(_.each(q.following,function(c){f=f.concat(x(c,a,g))}),e=e.concat(B(q["private"].event,a,g,"private")),f=f.concat(e),e=e.concat(C(q["private"].habit,a,g,"private",f)),q.updated=!1):(t[c].parents&&_.each(t[c].parents,function(c){f=
f.concat(x(c,a,g))}),e=e.concat(B(t[c].event,a,g,c)),f=f.concat(e),e=e.concat(C(t[c].habit,a,g,c,f)),t[c].updated=!1);return e}function B(c,a,g,e){var f=[];if(!c)return f;for(var d=0,m=c.length;d<m;d++)if(c[d].year===a&&c[d].month===g){var l=_.clone(c[d]);l.group=e;l.type="event";l.id=d;f[f.length]=l}return f}function C(c,a,g,e,f){function d(c,a,e){function g(c,a,d){var e=function(){return _.clone(l)},s=v.calendar(a,d),r={sunday:0,sun:0,"\u65e5\u66dc\u65e5":0,monday:1,mon:1,"\u6708\u66dc\u65e5":1,
tuesday:2,tue:2,"\u706b\u66dc\u65e5":2,wednesday:3,wed:3,"\u6c34\u66dc\u65e5":3,thursday:4,thu:4,"\u6728\u66dc\u65e5":4,friday:5,fri:5,"\u91d1\u66dc\u65e5":5,saturday:6,sat:6,"\u571f\u66dc\u65e5":6},m={January:0,Jan:0,"\u7766\u6708":0,February:1,Feb:1,"\u5982\u6708":1,March:2,Mar:2,"\u5f25\u751f":2,April:3,Apr:3,"\u536f\u6708":3,May:4,"\u7690\u6708":4,June:5,Jun:5,"\u6c34\u7121\u6708":5,July:6,Jul:6,"\u6587\u6708":6,August:7,Aug:7,"\u8449\u6708":7,September:8,Sep:8,"\u9577\u6708":8,October:9,Oct:9,
"\u795e\u7121\u6708":9,November:10,Nov:10,"\u971c\u6708":10,December:11,Dec:11,"\u5e2b\u8d70":11};if(u[a-MEMO_LIMIT])if(u[a-MEMO_LIMIT][d]){if(u[a-MEMO_LIMIT][d][c])return _.clone(u[a-MEMO_LIMIT][d][c])}else u[a-MEMO_LIMIT][d]={};else u[a-MEMO_LIMIT]=[],u[a-MEMO_LIMIT][d]={};var n=c.split(":")[0],b=c.split(":").slice(1).join(":"),k=[];if("not"===n)if(k=e(),"public-holiday"===b||"\u795d\u65e5"===b){e=x(0,a,d);b=0;for(s=e.length;b<s;b++)e[b]=e[b].date;k=_.difference(k,e);u[a-MEMO_LIMIT][d][c]=_.clone(k)}else if(0===
b.indexOf("year")||0===b.indexOf("month")||0===b.indexOf("date")||0===b.indexOf("day"))b=b.replace(/=/,":"),k=_.difference(e(),g(b,a,d));else{var q=b.split("=")[0],t=b.replace(/^.+?=/,""),t=t.replace(/^"(.+)"$/,"$1");_.each(f,function(a){if(a[q]===t||0===a[q].indexOf("[mes]")&&a[q].slice(5)===t)k=_.without(k,a.date)})}else if("range"===n)if(".."===b.slice(0,2))b="..."===b.slice(0,3)?b.slice(3):b.slice(2),k=e(),b=b.split("/"),h=new Date(parseInt(b[0],10),parseInt(b[1],10)-1,parseInt(b[2],10)),h.getFullYear()<
a||h.getFullYear()==a&&h.getMonth()<d?k=[]:h.getFullYear()==a&&h.getMonth()==d?(k=e(),k=_.filter(k,function(a){return a<=h.getDate()})):k=e();else if(".."===b.slice(-2))b="..."===b.slice(-3)?b.slice(0,-3):b.slice(0,-2),b=b.split("/"),p=new Date(parseInt(b[0],10),parseInt(b[1],10)-1,parseInt(b[2],10)),p.getFullYear()>a||p.getFullYear()==a&&p.getMonth()>d?k=[]:p.getFullYear()==a&&p.getMonth()==d?(k=e(),k=_.filter(k,function(a){return a>=p.getDate()})):k=e();else if(-1!==b.indexOf("..")){k=e();b=b.split("...");
1===b.length&&(b=b[0].split(".."));var s=[],r=[],p=b[0],h=b[1],b=h.substr(h.length-4,4),r=h.substr(h.length-5,5),p=p.split("/"),p=new Date(parseInt(p[0],10),parseInt(p[1],10)-1,parseInt(p[2],10));p.getFullYear()>a||p.getFullYear()==a&&p.getMonth()>d?s=[]:p.getFullYear()==a&&p.getMonth()==d?(s=e(),s=_.filter(s,function(a){return a>=p.getDate()})):s=e();"date"===b||"week"===b||"year"===b||"dates"===r||"weeks"===r||"years"===r?(m="date"===b||"week"===b||"year"===b?parseInt(h.substring(0,h.length-4),
10):parseInt(h.substring(0,h.length-5),10),h=new Date(p.getTime()),"date"===b||"dates"===r?h.setDate(h.getDate()+m):"week"===b||"weeks"===r?h.setDate(h.getDate()+7*m):"year"!==b&&"years"!==r||h.setFullYear(h.getFullYear()+m)):(h=h.split("/"),h=new Date(parseInt(h[0],10),parseInt(h[1],10)-1,parseInt(h[2],10)));h.getFullYear()<a||h.getFullYear()==a&&h.getMonth()<d?r=[]:h.getFullYear()==a&&h.getMonth()==d?(r=e(),r=_.filter(r,function(a){return a<=h.getDate()})):r=e();k=_.intersection(s,r)}else w("invalid selector.");
else if("from"!==n&&"to"!==n)if("date"===n)k[k.length]=parseInt(b,10);else if("month"===n)if(!m[b]&&parseInt(b,10)!=d+1||m[b]&&m[b]!=d)k=[];else{if(!m[b]&&parseInt(b,10)==d+1||m[b]&&m[b]==d)k=e()}else if("day"===n)if(b.match(/^\d/)){for(var b=b.match(/^(\d+)(?:st|nd|rd|th)-?(.+)$/),e=parseInt(b[1],10),y=r[b[2]],b=0;""===s[b][y];)b++;k[k.length]=s[b-1+e][y]}else y=r[b],_.some(s,function(a){""!==a[y]&&(k[k.length]=a[y])});else"year"===n?"leap-year"===b||"leap_year"===b||"\u3046\u308b\u3046\u5e74"===
b||"\u958f\u5e74"===b?(console.log("leap year"),k=0===a%400||0===a%4&&0!==a%100?e():[]):k=parseInt(b,10)!==a?[]:e():w('undefined key "'+n+'".');"day"===n&&(u[a-MEMO_LIMIT][d][c]=_.clone(k));return k}var d=[],l=_.flatten(v.calendar(a,e));_.each(c,function(c){1===c[1]?d[d.length]=g(c[0],a,e):0===c[1]&&("&&"===c[0]?d.push(_.intersection(d.pop(),d.pop())):"||"===c[0]?d.push(_.union(d.pop(),d.pop())):w("undefined operator "+c[0]))});1!=d.length&&(console.log(d),w("unexpected error in execSelectors()."));
return d.pop()}if(!c)return[];for(var m=[],l=0,q=c.length;l<q;l++){c[l].type="habit";c[l].group=e;var n=d(D(c[l].selector),a,g);_.each(n,function(d,f){n[f]={year:a,month:g,date:d,name:c[l].name,group:e,id:l,type:"habit"}});m=m.concat(n)}return m}function D(c){function a(a){""!==a[0]&&(g[g.length]=a)}if(z[c])return z[c];for(var g=[],e=!1,f=0,d=0,m=c.length;d<m;d++){var l=c.charAt(d);if(e)'"'===l?e=!1:"\\"===l&&(d+=1);else if('"'===l)e=!0;else if(" "===l){a([c.substring(f,d),1]);var l={" and ":"&&",
" \u304b\u3064 ":"&&"," && ":"&&"," or ":"||"," \u307e\u305f\u306f ":"||"," || ":"||"},q=!1,n;a:for(n in l)if(c.substr(d,n.length)===n){a([l[n],0]);f=d+n.length;d+=n.length;q=!0;break a}q||(a(["&&",0]),f=d+1,d+=1)}else if("("===l||")"===l)a([c.substring(f,d),1]),a([l,"("===l?2:3]),f=d+1}""!==c.substring(f)&&a([c.substring(f),1]);return z[c]=E(g)}function E(c){for(var a=[],g=[],e={"||":0,"&&":1},f=0,d=c.length;f<d;f++)if(1===c[f][1])g[g.length]=c[f].concat();else if(0===c[f][1]){var m=c[f][0];a[a.length-
1]&&e[m]<=e[a[a.length-1][0]]&&(g[g.length]=a.pop());a[a.length]=c[f]}else if(2===c[f][1])a[a.length]=c[f];else if(3===c[f][1]){for(;2!=a[a.length-1][1];)g[g.length]=a.pop(),0===a.length&&w("found mismatched parentheses");a.pop()}for(;0<a.length;)2===a[a.length-1][1]&&w("found mismatched parentheses."),g[g.length]=a.pop();return g}var u=[],z={};return{eventCalendar:function(c){for(var a=[],g=[],e=_.difference(q.following,q.hiddenGroup),f=0,d=e.length;f<d;f++)a[a.length]=x(e[f],v.year,v.month);q.isHiddenGroup(-1)||
(a[a.length]=x("private",v.year,v.month));f=0;for(d=a.length;f<d;f++)for(var e=0,m=a[f].length;e<m;e++)g[a[f][e].date]||(g[a[f][e].date]=[]),g[a[f][e].date][g[a[f][e].date].length]=a[f][e].id+":"+a[f][e].group+":"+a[f][e].type;return g[c]||[]},splitSelector:D}}]);
