angular.module(appName).factory("eventCal",["group","user","calF","$mdToast",function(r,l,v,B){function w(b){B.show(B.simple().content(b).position("top right"));console&&console.error&&console.error(b)}function x(b,a,h){if("private"!==b&&!r[b])return[];var e=[],d=[];"private"===b?(_.each(l.following,function(b){d=d.concat(x(b,a,h))}),e=e.concat(C(l["private"].event,a,h,"private")),d=d.concat(e),e=e.concat(D(l["private"].habit,a,h,"private",d)),l.updated=!1):(r[b].parents&&_.each(r[b].parents,function(b){d=
d.concat(x(b,a,h))}),e=e.concat(C(r[b].event,a,h,b)),d=d.concat(e),e=e.concat(D(r[b].habit,a,h,b,d)),r[b].updated=!1);return e}function C(b,a,h,e){var d=[];if(!b)return d;for(var c=0,n=b.length;c<n;c++)if(b[c].year===a&&b[c].month===h){var k=_.clone(b[c]);k.group=e;k.type="event";k.id=c;d[d.length]=k}return d}function D(b,a,h,e,d){function c(b,a,e){function h(b,a,c){var e=function(){return _.clone(k)},l=v.calendar(a,c),q={sunday:0,sun:0,"\u65e5\u66dc\u65e5":0,monday:1,mon:1,"\u6708\u66dc\u65e5":1,
tuesday:2,tue:2,"\u706b\u66dc\u65e5":2,wednesday:3,wed:3,"\u6c34\u66dc\u65e5":3,thursday:4,thu:4,"\u6728\u66dc\u65e5":4,friday:5,fri:5,"\u91d1\u66dc\u65e5":5,saturday:6,sat:6,"\u571f\u66dc\u65e5":6},u={January:0,Jan:0,"\u7766\u6708":0,February:1,Feb:1,"\u5982\u6708":1,March:2,Mar:2,"\u5f25\u751f":2,April:3,Apr:3,"\u536f\u6708":3,May:4,"\u7690\u6708":4,June:5,Jun:5,"\u6c34\u7121\u6708":5,July:6,Jul:6,"\u6587\u6708":6,August:7,Aug:7,"\u8449\u6708":7,September:8,Sep:8,"\u9577\u6708":8,October:9,Oct:9,
"\u795e\u7121\u6708":9,November:10,Nov:10,"\u971c\u6708":10,December:11,Dec:11,"\u5e2b\u8d70":11};if(s[a-MEMO_LIMIT])if(s[a-MEMO_LIMIT][c]){if(s[a-MEMO_LIMIT][c][b])return _.clone(s[a-MEMO_LIMIT][c][b])}else s[a-MEMO_LIMIT][c]={};else s[a-MEMO_LIMIT]=[],s[a-MEMO_LIMIT][c]={};var t=b.split(":")[0],f=b.split(":").slice(1).join(":"),g=[];if("not"===t)if(g=e(),"public-holiday"===f||"\u795d\u65e5"===f){l=x(0,a,c);q=0;for(f=l.length;q<f;q++)l[q]=l[q].date;g=_.difference(g,l);s[a-MEMO_LIMIT][c][b]=_.clone(g)}else if(0===
f.indexOf("year")||0===f.indexOf("month")||0===f.indexOf("date")||0===f.indexOf("day"))f=f.replace(/=/,":"),g=_.difference(e(),h(f,a,c));else{var r=f.split("=")[0],z=f.replace(/^.+?=/,""),z=z.replace(/^"(.+)"$/,"$1");_.each(d,function(a){if(a[r]===z||0===a[r].indexOf("[mes]")&&a[r].slice(5)===z)g=_.without(g,a.date)})}else if("from"===t)f=f.split("/"),n=new Date(parseInt(f[0],10),parseInt(f[1],10)-1,parseInt(f[2],10)),n.getFullYear()>a||n.getFullYear()==a&&n.getMonth()>c?g=[]:n.getFullYear()==a&&
n.getMonth()==c?(g=e(),g=_.filter(g,function(a){return a>=n.getDate()})):g=e(),null!=p&&p();else if("to"===t)g=e(),-1!==f.indexOf("/")?(f=f.split("/"),m=new Date(parseInt(f[0],10),parseInt(f[1],10)-1,parseInt(f[2],10)),m.getFullYear()<a||m.getFullYear()==a&&m.getMonth()<c?g=[]:m.getFullYear()==a&&m.getMonth()==c?(g=e(),g=_.filter(g,function(a){return a<=m.getDate()})):g=e()):(g=e(),p=function(b){return function(){var d=b.substr(b.length-4,4);if("date"===d||"week"===d||"year"===d)b=parseInt(b.substring(0,
b.length-4),10),m=new Date(n.getTime()),"date"===d?m.setDate(m.getDate()+b):"week"===d?m.setDate(m.getDate()+7*b):"year"===d&&m.setFullYear(m.getFullYear()+b);m.getFullYear()<a||m.getFullYear()==a&&m.getMonth()<c?g=[]:m.getFullYear()==a&&m.getMonth()==c?(g=e(),g=_.filter(g,function(a){return a<=m.getDate()})):g=e()}}(f),null!==n&&(p(),p=null));else if("date"===t)g[g.length]=parseInt(f,10);else if("month"===t)if(!u[f]&&parseInt(f,10)!=c+1||u[f]&&u[f]!=c)g=[];else{if(!u[f]&&parseInt(f,10)==c+1||u[f]&&
u[f]==c)g=e()}else if("day"===t)if(f.match(/^\d/)){for(var f=f.match(/^(\d+)(?:st|nd|rd|th)-?(.+)$/),u=parseInt(f[1],10),y=q[f[2]],q=0;""===l[q][y];)q++;g[g.length]=l[q-1+u][y]}else y=q[f],_.some(l,function(a){""!==a[y]&&(g[g.length]=a[y])});else"year"===t?"leap-year"===f||"leap_year"===f||"\u3046\u308b\u3046\u5e74"===f||"\u958f\u5e74"===f?(console.log("leap year"),g=0===a%400||0===a%4&&0!==a%100?e():[]):g=parseInt(f,10)!==a?[]:e():w('undefined key "'+t+'".');"day"===t&&(s[a-MEMO_LIMIT][c][b]=_.clone(g));
return g}var c=[],k=_.flatten(v.calendar(a,e)),n=null,m=null,p=null;_.each(b,function(b){1===b[1]?c[c.length]=h(b[0],a,e):0===b[1]&&("&&"===b[0]?c.push(_.intersection(c.pop(),c.pop())):"||"===b[0]?c.push(_.union(c.pop(),c.pop())):w("undefined operator "+b[0]))});1!=c.length&&(console.log(c),w("unexpected error in execSelectors()."));return c.pop()}if(!b)return[];for(var n=[],k=0,l=b.length;k<l;k++){b[k].type="habit";b[k].group=e;var p=c(E(b[k].selector),a,h);_.each(p,function(c,d){p[d]={year:a,month:h,
date:c,name:b[k].name,group:e,id:k,type:"habit"}});n=n.concat(p)}return n}function E(b){function a(a){""!==a[0]&&(h[h.length]=a)}if(A[b])return A[b];for(var h=[],e=!1,d=0,c=0,n=b.length;c<n;c++){var k=b.charAt(c);if(e)'"'===k?e=!1:"\\"===k&&(c+=1);else if('"'===k)e=!0;else if(" "===k){a([b.substring(d,c),1]);var k={" and ":"&&"," \u304b\u3064 ":"&&"," && ":"&&"," or ":"||"," \u307e\u305f\u306f ":"||"," || ":"||"},l=!1,p;a:for(p in k)if(b.substr(c,p.length)===p){a([k[p],0]);d=c+p.length;c+=p.length;
l=!0;break a}l||(a(["&&",0]),d=c+1,c+=1)}else if("("===k||")"===k)a([b.substring(d,c),1]),a([k,"("===k?2:3]),d=c+1}""!==b.substring(d)&&a([b.substring(d),1]);return A[b]=F(h)}function F(b){for(var a=[],h=[],e={"||":0,"&&":1},d=0,c=b.length;d<c;d++)if(1===b[d][1])h[h.length]=b[d].concat();else if(0===b[d][1]){var l=b[d][0];a[a.length-1]&&e[l]<=e[a[a.length-1][0]]&&(h[h.length]=a.pop());a[a.length]=b[d]}else if(2===b[d][1])a[a.length]=b[d];else if(3===b[d][1]){for(;2!=a[a.length-1][1];)h[h.length]=
a.pop(),0===a.length&&w("found mismatched parentheses");a.pop()}for(;0<a.length;)2===a[a.length-1][1]&&w("found mismatched parentheses."),h[h.length]=a.pop();return h}var s=[],A={};return{eventCalendar:function(b){for(var a=[],h=[],e=_.difference(l.following,l.hiddenGroup),d=0,c=e.length;d<c;d++)a[a.length]=x(e[d],v.year,v.month);l.isHiddenGroup(-1)||(a[a.length]=x("private",v.year,v.month));d=0;for(c=a.length;d<c;d++)for(var e=0,n=a[d].length;e<n;e++)h[a[d][e].date]||(h[a[d][e].date]=[]),h[a[d][e].date][h[a[d][e].date].length]=
a[d][e].id+":"+a[d][e].group+":"+a[d][e].type;return h[b]||[]},splitSelector:E}}]);
