angular.module(appName).factory("eventCal",["group","user","calF",function(p,n,m){function s(a,b,f,e){var c=[];if(!a)return c;for(var d=0,h=a.length;d<h;d++)if(a[d].month===f&&a[d].year===b){var t=_.clone(a[d]);t.group=e;t.type="event";t.id=d;c[c.length]=t}return c}function w(a,b,f){if("private"!==a&&!p[a])return[];var e=[],c=[];if("private"===a){for(var d=0,h=n.following.length;d<h;d++)c=c.concat(w(n.following[d],b,f));e=e.concat(s(n["private"].event,b,f,"private"));c=c.concat(e);e=e.concat(l(n["private"].habit,
b,f,"private",c));n.updated=!1}else{if(p[a].parents)for(d=0,h=p[a].parents.length;d<h;d++)c=c.concat(w(p[a].parents[d],b,f));e=e.concat(s(p[a].event,b,f,a));c=c.concat(e);e=e.concat(l(p[a].habit,b,f,a,c));p[a].updated=!1}return e}function l(a,b,f,e,c){function d(a){var e=[],d=function(){var c=_.flatten(m.calendar(b,f));return function(){return c}}(),h=null,k=null,l=null,r=[];_.each(a,function(a){if(a[1]===OTHERS){var u=a[0].split(":")[0];a=a[0].split(":").slice(1).join(":");var g=[];if("not"===u)if(g=
d(),"public-holiday"===a||"\u795d\u65e5"===a)for(var m=w(0,b,f),g=d(),q=0,s=m.length;q<s;q++)g=_.without(g,m[q].date);else if(0===a.indexOf("month"))-1!=a.indexOf(":")?f+1==a.split(":")[1]&&(g=[]):f+1==a.split("=")[1]&&(g=[]);else if(0===a.indexOf("date"))-1!=a.indexOf(":")?g=_.without(g,parseInt(a.split(":")[1],10)):-1!=a.indexOf("=")&&(g=_.without(g,parseInt(a.split("=")[1],10)));else for(var m=a.split("=")[0],x=a.replace(/^.+?=/,""),x=x.replace(/^"(.+)"$/,"$1"),q=0,s=c.length;q<s;q++)if(c[q][m]===
x||0===c[q][m].indexOf("[mes]")&&c[q][m].replace("[mes]","")===x)g=_.without(g,c[q].date);if("from"===u)a=a.split("/"),h=new Date(parseInt(a[0],10),parseInt(a[1],10)-1,parseInt(a[2],10)),h.getFullYear()>b||h.getFullYear()==b&&h.getMonth()>f?g=[]:h.getFullYear()==b&&h.getMonth()==f?(g=d(),g=_.filter(g,function(a){return a>=h.getDate()})):g=d(),null!=l&&l();else if("to"===u)g=d(),-1!==a.indexOf("/")?(a=a.split("/"),k=new Date(parseInt(a[0],10),parseInt(a[1],10)-1,parseInt(a[2],10)),k.getFullYear()<
b||k.getFullYear()==b&&k.getMonth()<f?g=[]:k.getFullYear()==b&&k.getMonth()==f?(g=d(),g=_.filter(g,function(a){return a<=k.getDate()})):g=d()):(g=d(),l=function(a){return function(){"date"===a.substr(a.length-4,4)?(a=parseInt(a.substring(0,a.length-4),10),k=new Date(h.getTime()),k.setDate(k.getDate()+a)):"week"===a.substr(a.length-4,4)?(a=parseInt(a.substring(0,a.length-4),10),k=new Date(h.getTime()),k.setDate(k.getDate()+7*a)):"year"===a.substr(a.length-4,4)&&(a=parseInt(a.substring(0,a.length-4),
10),k=new Date(h.getTime()),k.setFullYear(k.getFullYear()+a));k.getFullYear()<b||k.getFullYear()==b&&k.getMonth()<f?g=[]:k.getFullYear()==b&&k.getMonth()==f?(g=d(),g=_.filter(g,function(a){return a<=k.getDate()})):g=d()}}(a),null!==h&&(l(),l=null));else if("date"===u)g.push(parseInt(a,10));else if("month"===u)g=p[a]?p[a]!=f?[]:d():parseInt(a,10)!=f+1?[]:d();else if("day"===u)if(a.match(/^\d/)){a=a.match(/^(\d+)(?:st|nd|rd|th)-?(.+)$/);var u=parseInt(a[1],10),v=n[a[2]];for(a=0;!t[a][v];)a++;a=a-1+
u;-1===_.indexOf(r,t[a][v],!0)&&g.push(t[a][v])}else a=a.match(/^(.+)$/),v=n[a[1]],_.some(t,function(a){a[v]&&-1===_.indexOf(r,a[v],!0)&&g.push(a[v])});e.push(g)}else a[1]===OPERATOR&&("&&"===a[0]?e.push(_.intersectionObjects(e.pop(),e.pop())):"||"===a[0]&&e.push(_.unionObjects(e.pop(),e.pop())))});return e.pop()}if(!a)return[];for(var h=[],t=m.calendar(b,f),n={sunday:0,sun:0,"\u65e5\u66dc\u65e5":0,monday:1,mon:1,"\u6708\u66dc\u65e5":1,tuesday:2,tue:2,"\u706b\u66dc\u65e5":2,wednesday:3,wed:3,"\u6c34\u66dc\u65e5":3,
thursday:4,thu:4,"\u6728\u66dc\u65e5":4,friday:5,fri:5,"\u91d1\u66dc\u65e5":5,saturday:6,sat:6,"\u571f\u66dc\u65e5":6},p={January:0,Jan:0,"\u7766\u6708":0,February:1,Feb:1,"\u5982\u6708":1,March:2,Mar:2,"\u5f25\u751f":2,April:3,Apr:3,"\u536f\u6708":3,May:4,"\u7690\u6708":4,June:5,Jun:5,"\u6c34\u7121\u6708":5,July:6,Jul:6,"\u6587\u6708":6,August:7,Aug:7,"\u8449\u6708":7,September:8,Sep:8,"\u9577\u6708":8,October:9,Oct:9,"\u795e\u7121\u6708":9,November:10,Nov:10,"\u971c\u6708":10,December:11,Dec:11,
"\u5e2b\u8d70":11},r=0,s=a.length;r<s;r++){a[r].type="habit";a[r].group=e;var l=d(y(a[r].selector));_.each(l,function(c,d){l[d]={year:b,month:f,date:c,name:a[r].name,group:e,id:r,type:"habit"}});h=h.concat(l)}return h}function y(a){function b(a){""!==a[0]&&f.push(a)}for(var f=[],e=!1,c=0,d=0;d<a.length;d++)if(nowChar=a.charAt(d),e)'"'===nowChar&&(e=!1);else if('"'===nowChar)e=!0;else if(" "===nowChar){b([a.substring(c,d),OTHERS]);var h={and:"&&","\u304b\u3064":"&&","&&":"&&",or:"||","\u307e\u305f\u306f":"||",
"||":"||"},m=!1,l;a:for(l in h)if(a.substr(d,l.length+2)===" "+l+" "){b([h[l],OPERATOR]);c=d+l.length+2;d+=l.length+1;m=!0;break a}m||(b(["&&",OPERATOR]),c=d+1)}else"("===nowChar?(b([a.substring(c,d),OTHERS]),b(["(",LPARENTHESES]),c=d+1):")"===nowChar&&(b([a.substring(c,d),OTHERS]),b([")",RPARENTHESES]),c=d+1);""!==a.substring(c)&&b([a.substring(c),OTHERS]);return z(f)}function z(a){for(var b=[],f=[],e={"||":0,"&&":1},c=0,d=a.length;c<d;c++)if(a[c][1]===OTHERS)f.push(a[c].concat());else if(a[c][1]===
OPERATOR){var h=a[c][0];b[b.length-1]&&e[h]<=e[b[b.length-1][0]]&&f.push(b.pop());b.push(a[c])}else if(a[c][1]===LPARENTHESES)b.push(a[c]);else if(a[c][1]===RPARENTHESES){for(;b[b.length-1][1]!=LPARENTHESES;)f.push(b.pop()),0===b.length&&error("found mismatched parentheses");b.pop()}for(;0<b.length;)b[b.length-1][1]===LPARENTHESES&&error("found mismatched parentheses."),f.push(b.pop());return f}["OPERATOR","OTHERS","LPARENTHESES","RPARENTHESES"].reduce(function(a,b){window[b]=a;a++;return a},0);angular.toJson(n.hiddenGroup);
return{eventCalendar:function(a){for(var b=[],f=[],e=_.difference(n.following,n.hiddenGroup),c=0,d=e.length;c<d;c++)b[b.length]=w(e[c],m.year,m.month);n.isHiddenGroup(-1)||(b[b.length]=w("private",m.year,m.month));c=0;for(d=b.length;c<d;c++)for(var e=0,h=b[c].length;e<h;e++)f[b[c][e].date]||(f[b[c][e].date]=[]),f[b[c][e].date][f[b[c][e].date].length]=b[c][e].id+":"+b[c][e].group+":"+b[c][e].type;return f[a]||[]},filter:s,getEvents:w,habit:l,splitSelector:y}}]);
